version: "3.1"
services:
  db:
    image: "postgres:13"
    container_name: "gobank_db"
    environment:
      POSTGRES_PASSWORD: 23092023
      POSTGRES_USER: user
      POSTGRES_DB: gobank
    ports:
      - "5432:5432"
    volumes:
      - gobank_dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: "gobank_adminer"
    restart: always
    ports:
      - 8080:8080
volumes:
  gobank_dbdata:
